spring.datasource.url=${SPRING_NETBANK_DB_URL}
spring.datasource.username=${SPRING_NETBANK_DB_USER}
spring.datasource.password=${SPRING_NETBANK_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
